# -*- coding: utf-8 -*-
"""Exp8(Defuzzification operation ).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176Zr40NTt7RG_pCLDLuAzxopRBXdi14q
"""

!pip install -U scikit-fuzzy

import numpy as np
import matplotlib.pyplot as plt
import skfuzzy as fuzz


   # Generate trapezoidal membership function on range [0, 1]
x = np.arange(0, 5.05, 0.1)
mfx = fuzz.trapmf(x,[2, 2.5, 3, 4.5])

# Defuzzify this membership function five ways
defuzz_centroid = fuzz.defuzz(x, mfx, 'centroid') # Same as skfuzzy.centroid
defuzz_bisector = fuzz.defuzz(x, mfx, 'bisector')
defuzz_mom = fuzz.defuzz(x, mfx, 'mom')
defuzz_som = fuzz.defuzz(x, mfx, 'som')
defuzz_lom = fuzz.defuzz(x, mfx, 'lom')
defuzz_som
2.5

# Collect info for vertical lines
labels = ['centroid', 'bisector', 'mean of maximum', 'min of maximum',
            'max of maximum']
xvals = [defuzz_centroid,
           defuzz_bisector,
           defuzz_mom,
           defuzz_som,
           defuzz_lom]
colors = ['r', 'b', 'g', 'c', 'm']
ymax = [fuzz.interp_membership(x, mfx, i) for i in xvals]
defuzz_som
2.5

plt.figure(figsize=(12, 8))
plt.plot(x, mfx, 'k')
for xv, y, label, color in zip(xvals, ymax, labels, colors):
    plt.vlines(xv, 0, y, label=label, color=color)
plt.ylabel('Fuzzy membership')
plt.xlabel('Universe variable (arb)')
plt.ylim(-0.1, 1.1)
plt.legend(loc=2)
plt.show()